sudo: false

language: go

env:
  - SMVERSION=1.9

go:
  - "1.12.x"

matrix:
    fast_finish: true

addons:
    apt_packages:
      - lib32stdc++6
      - p7zip

install:
    - SMLATEST=`curl -s "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp client/Source-Chat-Relay.sp addons/sourcemod/scripting/
    - cp -r client/include/* addons/sourcemod/scripting/include
    - wget https://raw.githubusercontent.com/nefarius/sm-ext-socket/master/socket.inc -P addons/sourcemod/scripting/include/
    - wget https://raw.githubusercontent.com/rumblefrog/SM-ByteBuffer-Inc/master/bytebuffer.inc -P addons/sourcemod/scripting/include/
    - wget https://www.doctormckay.com/download/scripting/include/morecolors.inc -P addons/sourcemod/scripting/include/
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
    - chmod +x addons/sourcemod/scripting/spcomp
    - mkdir -p $TRAVIS_BUILD_DIR/build/game_server/addons/sourcemod/plugins
    - mkdir -p $TRAVIS_BUILD_DIR/build/scr-linux-amd64/relay_server/
    - mkdir -p $TRAVIS_BUILD_DIR/build/scr-arm-v7/relay_server/
    - mkdir -p $TRAVIS_BUILD_DIR/build/scr-windows-amd64/relay_server/

script:
    - go get -d ./server && go build -ldflags '-X config.SCRVER="git rev-parse HEAD" -extldflags "-static"' -o $TRAVIS_BUILD_DIR/build/scr-linux-amd64/relay_server/server ./server
    - export GOARCH=arm && export GOARM=7 && go build -ldflags '-X config.SCRVER="git rev-parse HEAD" -extldflags "-static"' -o $TRAVIS_BUILD_DIR/build/scr-arm-v7/relay_server/server ./server
    - export GOARCH=amd64 && export GOOS=windows && go get -d ./server && go build -ldflags '-X config.SCRVER="git rev-parse HEAD" -extldflags "-static"' -o $TRAVIS_BUILD_DIR/build/scr-windows-amd64/relay_server/server.exe ./server
    - ./addons/sourcemod/scripting/spcomp $TRAVIS_BUILD_DIR/client/Source-Chat-Relay -o $TRAVIS_BUILD_DIR/build/game_server/addons/sourcemod/plugins/Source-Chat-Relay.smx
    
    - cp server/config.toml.example build/scr-linux-amd64/relay_server
    - cp -R build/game_server build/scr-linux-amd64/

    - cp server/config.toml.example build/scr-arm-v7/relay_server
    - cp -R build/game_server build/scr-arm-v7/

    - cp server/config.toml.example build/scr-windows-amd64/relay_server
    - cp -R build/game_server build/scr-windows-amd64/

before_deploy:
    - cd $TRAVIS_BUILD_DIR/build/scr-linux-amd64/ && tar -czf $TRAVIS_BUILD_DIR/scr-linux-amd64.tar.gz *
    - cd $TRAVIS_BUILD_DIR/build/scr-arm-v7/ && tar -czf $TRAVIS_BUILD_DIR/scr-arm-v7.tar.gz *
    - cd $TRAVIS_BUILD_DIR/build/scr-windows-amd64/ && 7zr a $TRAVIS_BUILD_DIR/scr-windows-amd64.7z *

deploy:
    provider: releases
    api_key: "$githubkey"
    file:
        - $TRAVIS_BUILD_DIR/scr-linux-amd64.tar.gz
        - $TRAVIS_BUILD_DIR/scr-arm-v7.tar.gz
        - $TRAVIS_BUILD_DIR/scr-windows-amd64.7z
    skip_cleanup: true
    on:
        tags: true
