sudo: false

language: go

env:
  - SMVERSION=1.9

go:
  - "1.11.x"

matrix:
    fast_finish: true

addons:
    apt_packages:
      - lib32stdc++6

install:
    - SMLATEST=`curl -s "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp src/client/Source-Chat-Relay.sp addons/sourcemod/scripting/
    - cp src/client/include/morecolors.inc addons/sourcemod/scripting/include
    - cp src/client/include/socket.inc addons/sourcemod/scripting/include
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
    - go get -d ./src/server
    - chmod +x addons/sourcemod/scripting/spcomp

script:
    - go build -o ./out/server ./src/server
    - ./addons/sourcemod/scripting/spcomp $TRAVIS_BUILD_DIR/src/client/Source-Chat-Relay -o $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx

deploy:
    provider: releases
    api_key: "$githubkey"
    files:
        - $TRAVIS_BUILD_DIR/out/server
        - $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx
    skip_cleanup: true
    on:
        tags: true