sudo: false

language: go

env:
  - SMVERSION=1.9

go:
  - "1.12.x"

matrix:
    fast_finish: true

addons:
    apt_packages:
      - lib32stdc++6
      - p7zip

install:
    - SMLATEST=`curl -s "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp client/Source-Chat-Relay.sp addons/sourcemod/scripting/
    - cp -r client/include/* addons/sourcemod/scripting/include
    - wget https://raw.githubusercontent.com/nefarius/sm-ext-socket/master/socket.inc -P addons/sourcemod/scripting/include/
    - wget https://raw.githubusercontent.com/rumblefrog/SM-ByteBuffer-Inc/master/bytebuffer.inc -P addons/sourcemod/scripting/include/
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
    - chmod +x addons/sourcemod/scripting/spcomp

script:
    - go get -d ./server && go build -o ./out/linux-amd64/server ./server
    - export GOARCH=arm && export GOARM=7 && go build -o ./out/arm-v7/server ./server
    - export GOARCH=amd64 && export GOOS=windows && go get -d ./server && go build -o ./out/windows/server.exe ./server
    - ./addons/sourcemod/scripting/spcomp $TRAVIS_BUILD_DIR/client/Source-Chat-Relay -o $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx

before_deploy:
    - tar -czf scr-linux-amd64.tar.gz -C $TRAVIS_BUILD_DIR/out/linux-amd64 server -C $TRAVIS_BUILD_DIR/out/ Source-Chat-Relay.smx -C $TRAVIS_BUILD_DIR/ config.toml.example
    - tar -czf scr-arm-v7.tar.gz -C $TRAVIS_BUILD_DIR/out/arm-v7 server -C $TRAVIS_BUILD_DIR/out/ Source-Chat-Relay.smx -C $TRAVIS_BUILD_DIR/ config.toml.example
    - 7zr a scr-windows-amd64.7z $TRAVIS_BUILD_DIR/out/windows/server.exe $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx $TRAVIS_BUILD_DIR/config.toml.example

deploy:
    provider: releases
    api_key: "$githubkey"
    file:
        - $TRAVIS_BUILD_DIR/scr-linux-amd64.tar.gz
        - $TRAVIS_BUILD_DIR/scr-arm-v7.tar.gz
        - $TRAVIS_BUILD_DIR/scr-windows-amd64.7z
    skip_cleanup: true
    on:
        tags: true
