sudo: false

language: go

env:
  - SMVERSION=1.9

go:
  - "1.11.x"

matrix:
    fast_finish: true

addons:
    apt_packages:
      - lib32stdc++6

before_install:
    - echo go version

install:
    - SMLATEST=`curl "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp src/client/Source-Chat-Relay.sp addons/sourcemod/scripting/
    - cp src/client/include/socket.inc addons/sourcemod/scripting/include

before_script:
    - go get -t ./src/server
    - chmod +x addons/sourcemod/scripting/spcomp
    - chmod +x addons/sourcemod/scripting/compile.sh

script:
    - go build ./src/server -o ./src/server
    - ./addons/sourcemod/scripting/compile.sh ./src/client/Source-Chat-Relay -o Source-Chat-Relay.smx
