sudo: false

language: go

env:
  - SMVERSION=1.9

go:
  - "1.11.x"

matrix:
    fast_finish: true

addons:
    apt_packages:
      - lib32stdc++6
      - p7zip

install:
    - SMLATEST=`curl -s "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp client/Source-Chat-Relay.sp addons/sourcemod/scripting/
    - cp client/include/morecolors.inc addons/sourcemod/scripting/include
    - cp client/include/socket.inc addons/sourcemod/scripting/include
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
    - chmod +x addons/sourcemod/scripting/spcomp

script:
    - go get -d ./server && go build -o ./out/server ./server
    - export GOOS=windows && go get -d ./server && go build -o ./out/server.exe ./server
    - ./addons/sourcemod/scripting/spcomp $TRAVIS_BUILD_DIR/client/Source-Chat-Relay -o $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx

before_deploy:
    - 7zr a linux-amd64.tar.gz out/server $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx $TRAVIS_BUILD_DIR/config.toml.example
    - 7zr a windows-64.7z out/server.exe $TRAVIS_BUILD_DIR/out/Source-Chat-Relay.smx $TRAVIS_BUILD_DIR/config.toml.example

deploy:
    provider: releases
    api_key: "$githubkey"
    file:
        - $TRAVIS_BUILD_DIR/linux-amd64.tar.gz
        - $TRAVIS_BUILD_DIR/windows-64.7z
    skip_cleanup: true
    on:
        tags: true