[[General]]
Port = 57452 # Port to start the socket server on

[[Bot]]
Token = "BotToken" # The Bot's Token

[[Database]]
Host = "127.0.0.1" # MySQL Database Host
Username = "fishy" # MySQL Database Username
Password = "fish!" # MySQL User Password
Database = "relay" # MySQL Database To Use
Port = "3306" # MySQL Server Port
