[General]
Port = 57452 # Port to start the socket server on

[Bot]
Token = "NDQ0OTE2OTQ0NjAxMzUwMTQ0.Do2LLQ.re463avIQ37dthA5xPQYdKshBI0" # The Bot's Token

[Database]
Host = "127.0.0.1" # MySQL Database Host
Username = "root" # MySQL Database Username
Password = "" # MySQL User Password
Database = "relay" # MySQL Database To Use
Port = 3306 # MySQL Server Port
